on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the packages
        run: npm install     
   
      - name: build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action

     

      






 