on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v3
        with:
         name: my-artifact
         path: path/to/artifact/world.txt
         
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action

      






 