name: 'please release'

on: 
 push:
  branches:
    - main

jobs:
  pre-release:
    name: "Pre Re-lease"
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - uses: google-github-actions/release-please-action@v3.1.2
         with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: my-github-actions-2