name: 'please release'

on: [push]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - uses: google-github-actions/release-please-action@v3
         with:
          release-type: node
          package-name: my-github-actions-2

