name: 'please release'

on: 
 push:
  branches:
    - main

jobs:
  pre-release:
    name: "Pre Re-lease"
    runs-on: ubuntu-latest
    steps:
       - uses: google-github-actions/release-please-action@v3
         with:
          release-type: node
          package-name: my-github-actions-2