on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: making a folder
        run: mkdir downloads

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: my-first-artifact
          path: ./dist