name: "pre-release"

on:
  workflow_dispatch:
    inputs:
      choice: 
        type: choice
        description: Make a choice
        options:
          - major
          - minor
          - patch
       
# on:
#   push:
#     branches:
#       - "main"
#       - "feature/ticket2"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:  
      - uses: actions/checkout@v3
     
      - name: Install the packages
        run: npm install
        
      - name: Setup GitHub User
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "@${GITHUB_ACTOR}"
          
      - name: Bump Tag
        run: |
          npm run release -r patch

    